== NIT Environment

*Год,дата выпуска:* 2019

*Copyright:* (C) New Internet Technology Inc., 2018-2019

*Лицензия:* BSD (Open Source)

*Разрядность:* 32 bit

*Поддерживаемые платформы:* Microsoft Windows XP SP3, Microsoft Windows
7, Microsoft Windows 8.1, Microsoft Windows 10, Windows 2003 Server SP1,
Windows 2008 Server R2, Windows 2012 Server R2, Windows 2016 Server,
Windows 2019 Server,

New Internet Technologies Environment предназначена для первичной
конфигурации компьютера перед установкой админ-пака Exponenta.
Установленная программа скачивает необходимые компоненты из Интернета. В
общедоступной версии возможность автоматической скачки и установки
модулей заблокирована, однако возможна ручная установка всех доступных
модулей. Программа распространяется в 32-битном варианте, совместима с
операционными системами Microsoft Windows начиная с версии XP SP3.
Дополнительно к своей установке программа устанавливает PowerShell и
dotNet Framework 4.0, необходимые для установки менеджера пакетов
_chocolatey_. Программа полезна при начальной инициализации
компьютера/сервера Windows, расположенного на хостинге. Может также
устанавливаться на стационарные компьютеры.

Программа представляет собой Wix MSI инсталлятор, устанавливающий в
папку _Program Files_ основные скрипты для скачки и установки фирменного
программного обеспечения, а также устанавливающий переменные окружения.
По соображениям безопасности автоматическая скачка и установка фирменных
программ заблокирована, и должна производиться вручную из консоли из
папки с установленной программой. Это сделано с целью «не навреди
неопытному пользователю».

*_Категория:_* Windows конфигураторы | *_Добавил:_* yudenis | *Теги:*
Configurator, Exponenta, windows-конфигуратор, downloader and
installator, Windows 7, Windows Server, Windows 10, admin-pack, new
internet technologies, Windows XP SP3
